project:
  type: book
  resources:
    - src/**

book:
  title: "The Interactive Guide to Integer Factorization"
  subtitle: "From Trial Division to GNFS in Python"
  author: "Chiara Coetzee"
  date: "12/18/2025"
  chapters:
    - index.qmd
    - trial-division/index.qmd
    - primality-testing/index.qmd
    - references/index.qmd

  sidebar:
    logo: cover.png
    logo-alt: "The Interactive Guide to Integer Factorization cover"
    logo-href: /

bibliography: references.bib

format:
  live-html:
    toc: true
    css: styles.css
