project:
  type: book
  resources:
    - src/**

book:
  title: "From Trial Division to GNFS"
  subtitle: "Building modern integer factorization algorithms in Python"
  author: "Chiara Coetzee"
  date: "12/18/2025"
  chapters:
    - index.qmd
    - trial-division/index.qmd
    - references/index.qmd

  sidebar:
    logo: cover.png
    logo-alt: "From Trial Division to GNFS cover"
    logo-href: /
    title: |
      From Trial Division<br>to GNFS

bibliography: references.bib

format:
  live-html:
    toc: true
    css: styles.css
