project:
  type: book
  resources:
    - src/**

book:
  title: "From Trial Division to GNFS: Building modern integer factorization algorithms in Python"
  author: "Chiara Coetzee"
  date: "12/18/2025"
  chapters:
    - index.qmd
    - intro/index.qmd
    - summary/index.qmd
    - references/index.qmd

bibliography: references.bib

format:
  live-html:
    toc: true

execute:
  python: .venv/Scripts/python.exe
